version: "3.3"

services:
  fyp-panel:
    container_name: fyp-panel
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_API_URL=https://<CHANGEME>
    expose:
      - 3000:3000
    build:
      dockerfile: panel/Dockerfile
    networks:
      - fyp

  fyp-api:
    container_name: fyp-api
    restart: unless-stopped
    expose:
      - 8000:8000
    build:
      dockerfile: api/Dockerfile
    networks:
      - fyp

  fyp-traefik:
    image: traefik:latest
    container_name: fyp-traefik
    ports:
      - "8080:80"
      - "444:443"
    volumes:
      - ./traefik/traefik.yml:/traefik.yml:ro
      - ./traefik/config.yml:/config.yml:ro
    networks:
      - fyp

  fyp-db:
    container_name: fyp-db
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: CHANGEMEinsecurepassword!
      MYSQL_DATABASE: fyp
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - /opt/fyp-combined/db/data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - fyp

networks:
  fyp:
